# -*- coding: utf-8 -*-
"""DECISION_TREE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ff_n-0vj1Gjhl-LYIx7rgtovBMmxQU2b
"""

# Decision Tree
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Load dataset
src = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(src)

# Pre-processing
df = df[['Pclass', 'Sex', 'Age', 'Survived']].dropna()
lblenc = LabelEncoder()
df['Sex'] = lblenc.fit_transform(df['Sex'])

X = df[['Pclass', 'Sex', 'Age']]
y = df['Survived']

# Split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.32)

# Model training
c = DecisionTreeClassifier()
c.fit(x_train, y_train)

# Prediction
p = c.predict(x_test)
print("Accuracy:", accuracy_score(y_test, p))

