# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpNUdMR_31vIJVFxQh1wMVJjDUfvDCim
"""

# K-Nearest Neighbor
from sklearn.datasets import load_digits
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Load dataset
digits=load_digits()
x,y=digits.data, digits.target

# Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

# Model training
KNN=KNeighborsClassifier()
KNN.fit(x_train, y_train)

# Prediction
yp = KNN.predict(x_test)
print(classification_report(y_test, yp))

