# -*- coding: utf-8 -*-
"""LOGISTIC_REGRESSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baedVKPNGyrD_8VVGAZjaa-61-2r59hh
"""

# 1_logistic_regression

from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load data
iris = load_iris()
x,y= iris.data, iris.target

#splitting data
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3)

#Training model
model= LogisticRegression(max_iter=200)
model.fit(x_train, y_train)

#prediction
predictions=model.predict(x_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, predictions))

