# -*- coding: utf-8 -*-
"""RANDOM_FOREST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feFmLenm5F5gGQsYymhNiSoxUOizF_JI
"""

# Random Forest
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
wine=load_wine()
x,y=wine.data,wine.target

# Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

# Model training
ranfor = RandomForestClassifier()
ranfor.fit(x_train, y_train)

# Prediction
yp= ranfor.predict(x_test)
print("Accuracy:", accuracy_score(y_test, yp))

