# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmMr6rdOWyRpO3LIcct6iME1Vb8zLwYx
"""

# support vector machine
from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
data=load_breast_cancer()
x,y=data.data,data.target

# Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

# Model training
svm=SVC()
svm.fit(x_train, y_train)

# Prediction
yp=svm.predict(x_test)
print(accuracy_score(y_test,yp))

